### ISSUE TITLE
don't say goodbye to me without leaving contact method

### ISSUE THREAD

**Issue by jackkwong** [hanton/CopyIssue-Xcode-Plugin#1]
hey hanton, this is jack, just back from holiday and see your msg. 
kinda shocked to learn of the news, it was great time teaming with you, and I truly wish you best for your career.

Anyway, if you see this, this is my github account, you can reach me by my personal email also `kwong999999@gmail.com`, send me an email~

**Comment by hanton** [comment]
hi jack, i saw your msg yesterday, but didn't have time to reply, sorry ;)
it''s also great to work with you and get help from you.
my personal email is hanton.yang@gmail.com, will send you an email later :+1:
