### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by milanrathod87** [hanton/CopyIssue-Xcode-Plugin#18]
For any issue, If I select "Ask Google" OR "Ask Stackoverflow", It always search with key word "For R".

**Comment by dwicke01** [comment]
I haven't been able to reproduce the issue, can you provide additional information? Which browser and plugins are you using?

**Comment by milanrathod87** [comment]
Stackoverflow link:
In all browser, it opens stackoverflow link: http://stackoverflow.com/nocaptcha?s=455e1eee-4779-4ebf-b60b-9204b78e7183

Google link: 
In Safari it will simply open google.com and for rest of browser it will open this link: https://www.google.co.in/?&gfe_rd=cr&ei=0iftVcDtHbLG8Af5tqeIDQ#q=for%20R

**Comment by milanrathod87** [comment]
Hi Daniel,

Finally issue found.

If issue contains path to that file then this issue occurs.

For example:
../DAPP/DeshboardVC.m::23:17: Auto property synthesis will not synthesize property 'text' declared in protocol 'TTTAttributedLabel'

In above example path is ../DAPP/DeshboardVC.m 
and issue is Auto property synthesis will not synthesize property 'text' declared in protocol 'TTTAttributedLabel'

Hense while searching for issue it is necessary to remove file path.

**Comment by dwicke01** [comment]
Are you still having the issue?

**Comment by milanrathod87** [comment]
Hi Daniel,

Now it working fine but need to remove file name while searching.

For e.g. "PTKTextField.h:25:54: Auto property synthesis will not synthesize property ; it will be implemented by its superclass, use @dynamic to acknowledge intention"

Here it need to remove file name "PTKTextField.h:25:54:"

Thanks

**Comment by dwicke01** [comment]
Can you create a project with the error you're describing? I'm having trouble recreating the issue, and the regular expression being used should be filtering out filepaths already.

**Comment by milanrathod87** [comment]
Hi Daniel,

Actually I am using two files in my project namely "PTKTextField.h" and "PTKTextField.m".

This file name issue occurs in existing project but if I use same files in new project this issue gone.

I don't know the reason why this happened.

Thanks

**Comment by hanton** [comment]
Do you try uninstall and re-install `CopyIssue-Xcode-Plugin`? I guess the plugin in your old project need a refresh to use the improvement :)

**Comment by milanrathod87** [comment]
Yes I did it but same problem as describe in my previous comment.

**Comment by dwicke01** [comment]
Is the project with the search issue public? Or can you create a public one with the issue?

**Comment by milanrathod87** [comment]
I have looked on issue and issue is like if file path contains blank space then and then this issue occurs. Otherwise it will work fine.

Thanks

**Comment by dwicke01** [comment]
I just tried out that case and you're right about the formatting with the spaces. I just made a commit that should handle that case. Can you try it now?

**Comment by milanrathod87** [comment]
Hi Daniel,

Its working fine now. Thanks for resolving issue.

Thanks

**Comment by dwicke01** [comment]
No problem!
