### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mythodeia** [hanton/CopyIssue-Xcode-Plugin#26]
Hello
in Xcode v7.3 when i right click on an error it crashes and closes Xcode.
anything i can do for this?
El Capitan 10.11.4 (15E65)
Xcode Version 7.3 (7D175)

**Comment by dwicke01** [comment]
Sounds like a bug. I'm having trouble reproducing. Can you give more info? What kind or error is it? Does it happen with all errors or just certain ones? Are you using other plugins?

**Comment by mythodeia** [comment]
It crashes no matter the error. As soon as i right click it crashes Xcode. I tested it by simply removing a `;` from the end of an Obj-C line. Then went to the issue navigator and tried to right click at the error.
This is the list with the plugins i use.
![plugins](https://cloud.githubusercontent.com/assets/1748458/14289720/b52e460c-fb64-11e5-855c-e526a02d1162.png)

**Comment by dwicke01** [comment]
@mythodeia sorry for the delay, this appears to be a clash with AMAppExportToIPA. I installed all of the plugins on your list and that one seems to be preventing the context menu created from the issue navigator from having any items. This causes an exception when HTYCopyIssue tries to add an item at index 1. I could make a quick fix, although I believe the fix should be on their side, as my fix would cause a context menu with only my items. Let me know if uninstalling that plugin fixes the problem for you.

**Comment by mythodeia** [comment]
thanks a lot for your time and support. 
i have just informed the author of that plugin to take a look.
Hopefully he can provide a fix so we can enjoy both the plugins without using "hacks"

**Comment by mythodeia** [comment]
i downloaded a new version of the AMAppExportToIPA-Xcode-Plugin and now it works fine.
thanks for your support once again

**Comment by dwicke01** [comment]
No problem, glad people are using this

**Comment by mythodeia** [comment]
of course they are...saves a huge amount of time :+1:
