### ISSUE TITLE
Missing strings with quotation marks when 'Ask Google' and 'Ask Stackoverflow'

### ISSUE THREAD

**Issue by hanton** [hanton/CopyIssue-Xcode-Plugin#3]
For example, the Xcode error is: 
**Expected '{' after 'if' condition**

When 'Ask Google' or 'Ask Stackoverflow', the error becomes **Expected after condition**, strings with quotation marks, such as **'{'** and **'if'** are missing.

**Comment by florianbuerger** [comment]
I stripped them because most of the time they contain the name of a method or variable. Any bright idea to handle that? Most of the time the stripping was helpful but not sure if this tradeoff is the right thing to do.

**Comment by hanton** [comment]
umm... really. How about adding an option, and users are able to choose by themselves?

**Comment by florianbuerger** [comment]
Generally I am a strong opponent for opinionated software but I guess in this case there is no other option.

I'll look at it tomorrow.
