### ISSUE TITLE
Allow for other Google domains

### ISSUE THREAD

**Issue by jasdev** [hanton/CopyIssue-Xcode-Plugin#7]
Currently defaults to .de

https://github.com/hanton/CopyIssue-Xcode-Plugin/blob/f457599b38aee1d7bac844168b80cc8431a3356f/HTYCopyIssue/HTYCopyIssue.m#L136

**Comment by hanton** [comment]
Thanks @Jasdev , default goole search domain is changed to `google.com`
https://github.com/hanton/CopyIssue-Xcode-Plugin/commit/d2bea3731b6c0789ea1213d709ebbda52695f37b
